# SPI used by WebCore, either for temporary use (denoted by a bug URL) or
# permanent use.
#
# More info: https://github.com/WebKit/WebKit/wiki/Using-SPI-on-Apple-platforms

[accessibility."rdar://141698311"]
classes = ["AXRemoteElement"]
selectors = [
    { name = "setOnClientSide:", class = "?" },
    { name = "initWithUUID:andRemotePid:andContextId:", class = "?" },
]

[materials.not-web-essential]
classes = ["MTMaterialLayer"]
symbols = [
    "_MTCoreMaterialRecipeNone",
    "_MTCoreMaterialRecipePlatformChromeDark",
    "_MTCoreMaterialRecipePlatformChromeLight",
    "_MTCoreMaterialRecipePlatformContentDark",
    "_MTCoreMaterialRecipePlatformContentLight",
    "_MTCoreMaterialRecipePlatformContentThickDark",
    "_MTCoreMaterialRecipePlatformContentThickLight",
    "_MTCoreMaterialRecipePlatformContentThinDark",
    "_MTCoreMaterialRecipePlatformContentThinLight",
    "_MTCoreMaterialRecipePlatformContentUltraThinDark",
    "_MTCoreMaterialRecipePlatformContentUltraThinLight",
    "_MTCoreMaterialVisualStyleCategoryFill",
    "_MTCoreMaterialVisualStyleCategoryStroke",
    "_MTCoreMaterialVisualStyleNone",
    "_MTCoreMaterialVisualStylePrimary",
    "_MTCoreMaterialVisualStyleQuaternary",
    "_MTCoreMaterialVisualStyleSecondary",
    "_MTCoreMaterialVisualStyleSeparator",
    "_MTCoreMaterialVisualStyleTertiary",
    "_MTVisualStylingCreateDictionaryRepresentation",
]

[network.not-web-essential]
symbols = [
    # Only used for benchmarking, see 293525@main.
    "_nw_parameters_set_source_application_by_bundle_id",
]
