# SPI used by JavaScriptCore, either for temporary use (denoted by a bug URL)
# or permanent use.
#
# More info: https://github.com/WebKit/WebKit/wiki/Using-SPI-on-Apple-platforms

[runtime.not-web-essential]
symbols = ["_dyld_program_sdk_at_least"]
requires = ["USE_APPLE_INTERNAL_SDK"]

